services:
  - type: web
    name: traefik
    runtime: docker
    region: ohio
    plan: starter
    rootDir: whatshouldthisbe?
    dockerCommand:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=info@thieflord.dev"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
  - type: redis
    name: redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free
    command: ["redis-server", "--appendonly", "yes"]
  - type: web
    name: arena
    runtime: docker
    repo: https://github.com/bee-queue/arena.git --branch v2.8.1 /opt/arena
    region: ohio
    plan: starter
    rootDir: ???
    healthCheckPath: /
    envVars:
      - key: REDIS_HOST
        value: redis
  -  type: web
     name: fuseki
     runtime: docker
     envVars:
       - key: ADMIN_PASSWORD
         value: "1234!@#$qwerQWER"


  traefik:
    image: traefik:v2.3
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  fuseki:
    image: semapps/jena-fuseki-webacl
    volumes:
      - ./data/fuseki:/fuseki
    ports:
      - "3030:3030"
    expose:
      - "3030"

  middleware:
    build: ./middleware
    container_name: middleware
    depends_on:
      - fuseki
      - redis
    volumes:
      - ./middleware/logs:/app/boilerplate/logs
      - ./middleware/actors:/app/boilerplate/actors
      - ./middleware/jwt:/app/boilerplate/jwt
      - ./middleware/uploads:/app/boilerplate/uploads
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pods.rule=Host(`activity.thieflord.dev`)"
      - "traefik.http.routers.pods.entrypoints=websecure"
      - "traefik.http.routers.pods.tls.certresolver=myresolver"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - middleware
    restart: always
    expose:
      - "4000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.activity.thieflord.dev`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

  redis:
    expose:
      - "6379"
    volumes:
      - ./data/redis:/data


  arena:
    build: ./arena/Dockerfile
    restart: always
    volumes:
      - ./arena/config:/opt/arena/src/server/config
    depends_on:
      - redis
    ports:
      - "4567:4567"
